import { colorURL } from "../../components/ActivityCardItem";
import { IDataProps } from "../../interface/CardInterface";
export const selfAwareness: IDataProps[] = [
  {
    title: "Group Share",
    id: 101,
    description: "Self Awareness",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-2.png"),
    colorUrl: colorURL("Self Awareness"),
    saved: true,
  },
  {
    title: "Reflections",
    id: 102,
    description: "Self Awareness",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Self Awareness"),
    saved: false,
  },
  {
    title: "Lab Activity",
    id: 103,
    description: "Self Awareness",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Self Awareness"),
    saved: true,
  },
  {
    title: "Mindful Practices",
    id: 104,
    description: "Self Awareness",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Self Awareness"),
    saved: false,
  },
  {
    title: "Motivation Moment",
    id: 105,
    description: "Self Awareness",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Self Awareness"),
    saved: true,
  },
  {
    title: "Vocabulary Chart",
    id: 106,
    description: "Self Awareness",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Self Awareness"),
    saved: true,
  },
];

export const socialAwareness: IDataProps[] = [
  {
    title: "Group Share",
    id: 111,
    description: "Social Awareness",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-2.png"),
    colorUrl: colorURL("Social Awareness"),
    saved: true,
  },
  {
    title: "Reflections",
    id: 112,
    description: "Social Awareness",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Social Awareness"),
    saved: false,
  },
  {
    title: "Lab Activity",
    id: 113,
    description: "Social Awareness",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Social Awareness"),
    saved: true,
  },
  {
    title: "Mindful Practices",
    id: 114,
    description: "Social Awareness",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Social Awareness"),
    saved: false,
  },
  {
    title: "Motivation Moment",
    id: 115,
    description: "Social Awareness",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Social Awareness"),
    saved: true,
  },
  {
    title: "Vocabulary Chart",
    id: 116,
    description: "Social Awareness",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Social Awareness"),
    saved: true,
  },
];

export const relationshipSkills: IDataProps[] = [
  {
    title: "Group Share",
    id: 121,
    description: "Relationship Skills",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-2.png"),
    colorUrl: colorURL("Relationship Skills"),
    saved: true,
  },
  {
    title: "Reflections",
    id: 122,
    description: "Relationship Skills",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Relationship Skills"),
    saved: false,
  },
  {
    title: "Lab Activity",
    id: 123,
    description: "Relationship Skills",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Relationship Skills"),
    saved: true,
  },
  {
    title: "Mindful Practices",
    id: 124,
    description: "Relationship Skills",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Relationship Skills"),
    saved: false,
  },
  {
    title: "Motivation Moment",
    id: 125,
    description: "Relationship Skills",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Relationship Skills"),
    saved: true,
  },
  {
    title: "Vocabulary Chart",
    id: 126,
    description: "Relationship Skills",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Relationship Skills"),
    saved: true,
  },
];

export const decisionMaking: IDataProps[] = [
  {
    title: "Group Share",
    id: 131,
    description: "Decision Making",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-2.png"),
    colorUrl: colorURL("Decision Making"),
    saved: true,
  },
  {
    title: "Reflections",
    id: 132,
    description: "Decision Making",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Decision Making"),
    saved: false,
  },
  {
    title: "Lab Activity",
    id: 133,
    description: "Decision Making",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Decision Making"),
    saved: true,
  },
  {
    title: "Mindful Practices",
    id: 134,
    description: "Decision Making",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Decision Making"),
    saved: false,
  },
  {
    title: "Motivation Moment",
    id: 135,
    description: "Decision Making",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Decision Making"),
    saved: true,
  },
  {
    title: "Vocabulary Chart",
    id: 136,
    description: "Decision Making",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Decision Making"),
    saved: true,
  },
];

export const selfManagement: IDataProps[] = [
  {
    title: "Group Share",
    id: 141,
    description: "Self Management",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-2.png"),
    colorUrl: colorURL("Self Management"),
    saved: true,
  },
  {
    title: "Reflections",
    id: 142,
    description: "Self Management",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Self Management"),
    saved: false,
  },
  {
    title: "Lab Activity",
    id: 143,
    description: "Social Awareness",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Self Management"),
    saved: true,
  },
  {
    title: "Mindful Practices",
    id: 144,
    description: "Self Management",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Self Management"),
    saved: false,
  },
  {
    title: "Motivation Moment",
    id: 145,
    description: "Self Management",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Self Management"),
    saved: true,
  },
  {
    title: "Vocabulary Chart",
    id: 146,
    description: "Self Management",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Self Management"),
    saved: true,
  },
];
