import { colorURL } from "../../components/ActivityCardItem";
import { IDataProps } from "../../interface/CardInterface";
export const ActivitiesData: IDataProps[] = [
  {
    title: "Group Share",
    id: 101,
    description: "Self Awareness",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-2.png"),
    colorUrl: colorURL("Self Awareness"),
    saved: true,
  },
  {
    title: "Reflections",
    id: 102,
    description: "Self Awareness",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Self Awareness"),
    saved: false,
  },
  {
    title: "Lab Activity",
    id: 103,
    description: "Self Awareness",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Self Awareness"),
    saved: true,
  },
  {
    title: "Mindful Practice",
    id: 104,
    description: "Self Awareness",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Self Awareness"),
    saved: false,
  },
  {
    title: "Motivation Moment",
    id: 105,
    description: "Self Awareness",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Self Awareness"),
    saved: true,
  },
  {
    title: "Vocabulary Chart",
    id: 106,
    description: "Self Awareness",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Self Awareness"),
    saved: true,
  },
  {
    title: "Group Share",
    id: 107,
    description: "Social Awareness",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-2.png"),
    colorUrl: colorURL("Social Awareness"),
    saved: true,
  },
  {
    title: "Reflections",
    id: 108,
    description: "Social Awareness",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Social Awareness"),
    saved: false,
  },
  {
    title: "Lab Activity",
    id: 109,
    description: "Social Awareness",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Social Awareness"),
    saved: true,
  },
  {
    title: "Mindful Practice",
    id: 110,
    description: "Social Awareness",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Social Awareness"),
    saved: false,
  },
  {
    title: "Motivation Moment",
    id: 111,
    description: "Social Awareness",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Social Awareness"),
    saved: true,
  },
  {
    title: "Vocabulary Chart",
    id: 112,
    description: "Social Awareness",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Social Awareness"),
    saved: true,
  },
  {
    title: "Group Share",
    id: 113,
    description: "Relationship Skills",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-2.png"),
    colorUrl: colorURL("Relationship Skills"),
    saved: true,
  },
  {
    title: "Reflections",
    id: 114,
    description: "Relationship Skills",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Relationship Skills"),
    saved: false,
  },
  {
    title: "Lab Activity",
    id: 115,
    description: "Relationship Skills",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Relationship Skills"),
    saved: true,
  },
  {
    title: "Mindful Practice",
    id: 116,
    description: "Relationship Skills",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Relationship Skills"),
    saved: false,
  },
  {
    title: "Motivation Moment",
    id: 117,
    description: "Relationship Skills",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Relationship Skills"),
    saved: true,
  },
  {
    title: "Vocabulary Chart",
    id: 118,
    description: "Relationship Skills",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Relationship Skills"),
    saved: true,
  },
  {
    title: "Group Share",
    id: 119,
    description: "Decision Making",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-2.png"),
    colorUrl: colorURL("Decision Making"),
    saved: true,
  },
  {
    title: "Reflections",
    id: 120,
    description: "Decision Making",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Decision Making"),
    saved: false,
  },
  {
    title: "Lab Activity",
    id: 121,
    description: "Decision Making",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Decision Making"),
    saved: true,
  },
  {
    title: "Mindful Practice",
    id: 122,
    description: "Decision Making",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Decision Making"),
    saved: false,
  },
  {
    title: "Motivation Moment",
    id: 123,
    description: "Decision Making",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Decision Making"),
    saved: true,
  },
  {
    title: "Vocabulary Chart",
    id: 124,
    description: "Decision Making",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Decision Making"),
    saved: true,
  },
  {
    title: "Group Share",
    id: 125,
    description: "Self Management",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-2.png"),
    colorUrl: colorURL("Self Management"),
    saved: true,
  },
  {
    title: "Reflections",
    id: 126,
    description: "Self Management",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Self Management"),
    saved: false,
  },
  {
    title: "Lab Activity",
    id: 127,
    description: "Social Awareness",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Self Management"),
    saved: true,
  },
  {
    title: "Mindful Practice",
    id: 128,
    description: "Self Management",
    length: "Length: 20 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-4.png"),
    colorUrl: colorURL("Self Management"),
    saved: false,
  },
  {
    title: "Motivation Moment",
    id: 129,
    description: "Self Management",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Self Management"),
    saved: true,
  },
  {
    title: "Vocabulary Chart",
    id: 130,
    description: "Self Management",
    length: "Length: 30 minutes",
    imgUrl: require("../../../assets/images/activity-plan/activity-plan-1.png"),
    colorUrl: colorURL("Self Management"),
    saved: true,
  },
];

export default ActivitiesData;
